package com.ffi.category

/*
import io.realm.RealmObject
import io.realm.annotations.PrimaryKey

class Search : RealmObject() {
    private var searchHistory: String? = null
    private var userId: String? = null

    @PrimaryKey
    var id = 0
        set(userId) {
            field = id
        }

    // Standard getters & setters generated by your IDE…
    fun getsearchHistory(): String? {
        return searchHistory
    }

    fun setsearchHistory(searchHistory: String?) {
        this.searchHistory = searchHistory
    }

    fun getuserId(): String? {
        return userId
    }

    fun setuserId(userId: String?) {
        this.userId = userId
    }
}*/
