package com.ffi.category;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class SearchHome extends RealmObject {

    private String searchHistory;
    private String userId;

    @PrimaryKey
    private int id;

    // Standard getters & setters generated by your IDE…
    public String getsearchHistory() {
        return searchHistory;
    }

    public void setsearchHistory(String searchHistory) {
        this.searchHistory = searchHistory;
    }

    public String getuserId() {
        return userId;
    }

    public void setuserId(String userId) {
        this.userId = userId;
    }

    public int getId() {
        return id;
    }

    public void setId(int userId) {
        this.id = id;
    }

}